from agents.router import AgentRouter
from security.core import SecurityLayer
from services.semantic_cache.service import SemanticCache
import concurrent.futures
import threading

class App:
    def __init__(
        self,
        router: AgentRouter,
        session_id: str,
    ):
        self.router = router
        self.session_id = session_id
        self.security_layer = SecurityLayer()
        self.semantic_cache = SemanticCache(db_dir="./databases/responses_cache_db", enable_ttl=True)

    def _run(self, user_query: str) -> str:
        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
            cache_future = executor.submit(self.semantic_cache.get_similar, user_query)
            security_future = executor.submit(self.security_layer.process, user_query)

            cached_response = cache_future.result()
            is_safe, reason, _ = security_future.result()
        
        if not is_safe:
            return f"Security check failed: {reason}"
        
        if cached_response["response"]:
            return cached_response["response"]

        
        result = self.router.run(user_query=user_query)

        out = result.get("answer", None)

        if out:
            _, clean_output, _ = self.security_layer.validate_output(out, user_query)
            
            threading.Thread(
            target=self.semantic_cache.add_to_cache,
            args=(user_query, clean_output),
            daemon=True
            ).start()
            
            return clean_output
        
        else:
            return "No answer generated by agent."        

    def run_interactive(self,):
        print("Playground interactive CLI. Type 'exit' or Ctrl-C to quit.")
        while True:
            try:
                user_query = input("You: ")
                if not user_query or user_query.strip().lower() in {"exit", "quit"}:
                    print("Goodbye")
                    return

                answer = self._run(user_query)
                                
                print("Assistant:", answer)
                
            except KeyboardInterrupt:
                print("\nInterrupted. Exiting.")
                return
            except Exception as exc:
                print("Error during request:", exc)
